highlighter: pygments
permalink: pretty
markdown: kramdown

title: OpenCATS Applicant Tracking System
description: "OpenCATS - the free open-source ATS"

news:
    name: OpenCATS Newsletter
    authors: OpenCATS Community
    url: http://opencats.org/news
    feed: /news.xml

url: "http://opencats.org"

gems:
    - jekyll-redirect-from
    - jekyll-mentions
    - jekyll-sitemap

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
    
